// plantData.js
const plantData = {
  "Snake Plant": {
    wateringDays: 14,
    mistingDays: 30,
    repotMonths: 24,
    temperature: "60-85°F",
    soilType: "Well-draining cactus/succulent mix",
    toxicity: "Toxic"
  },
  "Peace Lily": {
    wateringDays: 7,
    mistingDays: 7,
    repotMonths: 12,
    temperature: "65-80°F",
    soilType: "Rich, well-draining soil",
    toxicity: "Toxic"
  },
  "Spider Plant": {
    wateringDays: 7,
    mistingDays: 14,
    repotMonths: 18,
    temperature: "65-75°F",
    soilType: "Well-draining potting mix",
    toxicity: "Non-toxic"
  },
  "Pothos": {
    wateringDays: 10,
    mistingDays: 30,
    repotMonths: 18,
    temperature: "60-85°F",
    soilType: "Well-draining soil",
    toxicity: "Toxic"
  },
  "ZZ Plant": {
    wateringDays: 21,
    mistingDays: null,
    repotMonths: 24,
    temperature: "65-75°F",
    soilType: "Well-draining soil",
    toxicity: "Toxic"
  },
  "Fiddle Leaf Fig": {
    wateringDays: 7,
    mistingDays: null,
    repotMonths: 12,
    temperature: "65-75°F",
    soilType: "Loamy, well-draining soil",
    toxicity: "Toxic"
  },
  "Rubber Plant": {
    wateringDays: 10,
    mistingDays: 14,
    repotMonths: 18,
    temperature: "60-75°F",
    soilType: "Well-draining potting soil",
    toxicity: "Toxic"
  },
  "Philodendron": {
    wateringDays: 10,
    mistingDays: 14,
    repotMonths: 18,
    temperature: "65-80°F",
    soilType: "Peat-based soil mix",
    toxicity: "Toxic"
  },
  "Calathea": {
    wateringDays: 5,
    mistingDays: 3,
    repotMonths: 12,
    temperature: "65-80°F",
    soilType: "Moist, well-draining soil",
    toxicity: "Non-toxic"
  },
  "Jade (Succulent)": {
    wateringDays: 21,
    mistingDays: null,
    repotMonths: 36,
    temperature: "60-75°F",
    soilType: "Cactus/succulent soil",
    toxicity: "Toxic"
  },
  // === 50 More Plants Below ===
  "Aloe Vera": {
    wateringDays: 14,
    mistingDays: null,
    repotMonths: 24,
    temperature: "55-80°F",
    soilType: "Cactus mix",
    toxicity: "Toxic"
  },
  "Areca Palm": {
    wateringDays: 7,
    mistingDays: 7,
    repotMonths: 24,
    temperature: "65-75°F",
    soilType: "Well-draining soil",
    toxicity: "Non-toxic"
  },
  "Boston Fern": {
    wateringDays: 3,
    mistingDays: 2,
    repotMonths: 12,
    temperature: "60-75°F",
    soilType: "Peaty, moist soil",
    toxicity: "Non-toxic"
  },
  "Bird's Nest Fern": {
    wateringDays: 5,
    mistingDays: 3,
    repotMonths: 12,
    temperature: "60-80°F",
    soilType: "Moist, well-draining soil",
    toxicity: "Non-toxic"
  },
  "Chinese Evergreen": {
    wateringDays: 10,
    mistingDays: 7,
    repotMonths: 18,
    temperature: "65-80°F",
    soilType: "Well-draining potting mix",
    toxicity: "Toxic"
  },
  "Dieffenbachia": {
    wateringDays: 7,
    mistingDays: 7,
    repotMonths: 12,
    temperature: "65-75°F",
    soilType: "Rich, well-draining soil",
    toxicity: "Toxic"
  },
  "Dracaena Marginata": {
    wateringDays: 10,
    mistingDays: 14,
    repotMonths: 18,
    temperature: "65-80°F",
    soilType: "Well-draining soil",
    toxicity: "Toxic"
  },
  "English Ivy": {
    wateringDays: 7,
    mistingDays: 5,
    repotMonths: 12,
    temperature: "50-70°F",
    soilType: "Rich, well-draining soil",
    toxicity: "Toxic"
  },
  "Echeveria": {
    wateringDays: 14,
    mistingDays: null,
    repotMonths: 24,
    temperature: "60-80°F",
    soilType: "Cactus soil",
    toxicity: "Non-toxic"
  },
  "Golden Barrel Cactus": {
    wateringDays: 21,
    mistingDays: null,
    repotMonths: 36,
    temperature: "50-85°F",
    soilType: "Sandy cactus mix",
    toxicity: "Non-toxic"
  },
"Monstera Deliciosa": {
  wateringDays: 7,
  mistingDays: 7,
  repotMonths: 12,
  temperature: "65-85°F",
  soilType: "Well-draining peat-based mix",
  toxicity: "Toxic"
},
"Chinese Money Plant": {
  wateringDays: 7,
  mistingDays: 14,
  repotMonths: 12,
  temperature: "60-75°F",
  soilType: "Well-draining potting soil",
  toxicity: "Non-toxic"
},
"Parlor Palm": {
  wateringDays: 7,
  mistingDays: 14,
  repotMonths: 24,
  temperature: "65-80°F",
  soilType: "Well-draining potting mix",
  toxicity: "Non-toxic"
},
"Bird of Paradise": {
  wateringDays: 7,
  mistingDays: 7,
  repotMonths: 12,
  temperature: "65-85°F",
  soilType: "Rich, well-draining soil",
  toxicity: "Toxic"
},
"String of Pearls": {
  wateringDays: 14,
  mistingDays: null,
  repotMonths: 24,
  temperature: "70-80°F",
  soilType: "Cactus/succulent mix",
  toxicity: "Toxic"
},
"String of Hearts": {
  wateringDays: 10,
  mistingDays: null,
  repotMonths: 18,
  temperature: "60-80°F",
  soilType: "Well-draining soil",
  toxicity: "Toxic"
},
"Air Plant (Tillandsia)": {
  wateringDays: 7,
  mistingDays: 2,
  repotMonths: null,
  temperature: "50-90°F",
  soilType: "No soil needed",
  toxicity: "Non-toxic"
},
"Cast Iron Plant": {
  wateringDays: 14,
  mistingDays: 14,
  repotMonths: 24,
  temperature: "60-75°F",
  soilType: "Well-draining soil",
  toxicity: "Non-toxic"
},
"Prayer Plant": {
  wateringDays: 5,
  mistingDays: 3,
  repotMonths: 12,
  temperature: "65-75°F",
  soilType: "Moist, well-draining soil",
  toxicity: "Non-toxic"
},
"Kentia Palm": {
  wateringDays: 10,
  mistingDays: 7,
  repotMonths: 24,
  temperature: "60-85°F",
  soilType: "Well-draining soil",
  toxicity: "Non-toxic"
},
"Flamingo Flower (Anthurium)": {
  wateringDays: 7,
  mistingDays: 7,
  repotMonths: 12,
  temperature: "65-80°F",
  soilType: "Rich, well-draining soil",
  toxicity: "Toxic"
},
"Orchid (Phalaenopsis)": {
  wateringDays: 7,
  mistingDays: 3,
  repotMonths: 12,
  temperature: "65-75°F",
  soilType: "Orchid bark mix",
  toxicity: "Non-toxic"
},
"Money Tree (Pachira aquatica)": {
  wateringDays: 10,
  mistingDays: 7,
  repotMonths: 18,
  temperature: "65-80°F",
  soilType: "Well-draining soil",
  toxicity: "Non-toxic"
},
"Japanese Aralia": {
  wateringDays: 7,
  mistingDays: 7,
  repotMonths: 24,
  temperature: "60-75°F",
  soilType: "Moist, well-draining soil",
  toxicity: "Non-toxic"
},
"China Doll Plant": {
  wateringDays: 7,
  mistingDays: 7,
  repotMonths: 12,
  temperature: "65-75°F",
  soilType: "Well-draining soil",
  toxicity: "Non-toxic"
},
"Swedish Ivy": {
  wateringDays: 7,
  mistingDays: 7,
  repotMonths: 18,
  temperature: "60-75°F",
  soilType: "Well-draining soil",
  toxicity: "Non-toxic"
},
"Maranta 'Lemon Lime'": {
  wateringDays: 5,
  mistingDays: 3,
  repotMonths: 12,
  temperature: "65-75°F",
  soilType: "Moist, well-draining soil",
  toxicity: "Non-toxic"
},
"Dracaena Marginata": {
  wateringDays: 10,
  mistingDays: 14,
  repotMonths: 18,
  temperature: "65-80°F",
  soilType: "Well-draining soil",
  toxicity: "Toxic"
},
"Golden Barrel Cactus": {
  wateringDays: 21,
  mistingDays: null,
  repotMonths: 36,
  temperature: "50-85°F",
  soilType: "Sandy cactus mix",
  toxicity: "Non-toxic"
},
"String of Bananas": {
  wateringDays: 14,
  mistingDays: null,
  repotMonths: 24,
  temperature: "65-80°F",
  soilType: "Cactus/succulent mix",
  toxicity: "Toxic"
},
"Alocasia Polly": {wateringDays: 7, mistingDays: 3, repotMonths: 12, temperature: "65-80°F", soilType: "Moist, well-draining soil", toxicity: "Toxic"},
"Aglaonema (Chinese Evergreen)": {wateringDays: 10, mistingDays: 7, repotMonths: 18, temperature: "65-80°F", soilType: "Well-draining potting mix", toxicity: "Toxic"},
"Croton": {wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-85°F", soilType: "Rich, well-draining soil", toxicity: "Toxic"},
"Dracaena Fragrans (Corn Plant)": {wateringDays: 10, mistingDays: 14, repotMonths: 18, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic"},
"Ficus Benjamina (Weeping Fig)": {wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-75°F", soilType: "Well-draining potting soil", toxicity: "Toxic"},
"Ficus Elastica (Rubber Tree)": {wateringDays: 10, mistingDays: 14, repotMonths: 18, temperature: "60-75°F", soilType: "Well-draining potting soil", toxicity: "Toxic"},
"Ficus Lyrata (Fiddle Leaf Fig)": {wateringDays: 7, mistingDays: null, repotMonths: 12, temperature: "65-75°F", soilType: "Loamy, well-draining soil", toxicity: "Toxic"},
"Maranta Leuconeura (Prayer Plant)": {wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-75°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic"},
"Nephrolepis exaltata (Boston Fern)": {wateringDays: 3, mistingDays: 2, repotMonths: 12, temperature: "60-75°F", soilType: "Peaty, moist soil", toxicity: "Non-toxic"},
"Peperomia": {wateringDays: 7, mistingDays: 14, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining potting mix", toxicity: "Non-toxic"},
"Sansevieria Trifasciata (Snake Plant)": {wateringDays: 14, mistingDays: 30, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining cactus/succulent mix", toxicity: "Toxic"},
"Schefflera (Umbrella Plant)": {wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining potting soil", toxicity: "Toxic"},
"Spathiphyllum (Peace Lily)": {wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Rich, well-draining soil", toxicity: "Toxic"},
"Syngonium Podophyllum (Arrowhead Plant)": {wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining potting mix", toxicity: "Toxic"},
"Tradescantia Zebrina (Wandering Jew)": {wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "60-75°F", soilType: "Moist, well-draining soil", toxicity: "Toxic"},
"Zamioculcas Zamiifolia (ZZ Plant)": {wateringDays: 21, mistingDays: null, repotMonths: 24, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Toxic"},
"Astrophytum Myriostigma (Bishop's Cap Cactus)": {wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-80°F", soilType: "Cactus mix", toxicity: "Non-toxic"},
"Epiphyllum Oxypetalum (Queen of the Night)": {wateringDays: 7, mistingDays: 3, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining potting mix", toxicity: "Non-toxic"},
"Mammillaria Hahniana (Old Lady Cactus)": {wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-80°F", soilType: "Cactus mix", toxicity: "Non-toxic"},
"Opuntia Microdasys (Bunny Ears Cactus)": {wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus/succulent mix", toxicity: "Non-toxic"},
"Alocasia (Elephant Ear)": { wateringDays: 7, mistingDays: 3, repotMonths: 12, temperature: "65-80°F", soilType: "Moist, well-draining soil", toxicity: "Toxic" },
"Arrowhead Plant (Syngonium)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Baby Rubber Plant (Peperomia obtusifolia)": { wateringDays: 10, mistingDays: 14, repotMonths: 18, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Begonia": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Bird of Paradise (Strelitzia reginae)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Rich, well-draining soil", toxicity: "Toxic" },
"Cast Iron Plant (Aspidistra elatior)": { wateringDays: 14, mistingDays: 14, repotMonths: 24, temperature: "60-75°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Chinese Evergreen (Aglaonema)": { wateringDays: 10, mistingDays: 7, repotMonths: 18, temperature: "65-80°F", soilType: "Well-draining potting mix", toxicity: "Toxic" },
"Croton (Codiaeum variegatum)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Dracaena (Dracaena spp.)": { wateringDays: 10, mistingDays: 14, repotMonths: 18, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Fiddle Leaf Fig (Ficus lyrata)": { wateringDays: 7, mistingDays: null, repotMonths: 12, temperature: "65-75°F", soilType: "Loamy, well-draining soil", toxicity: "Toxic" },
"Hoya (Wax Plant)": { wateringDays: 14, mistingDays: 7, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Jade Plant (Crassula ovata)": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "60-75°F", soilType: "Cactus/succulent soil", toxicity: "Toxic" },
"Kentia Palm (Howea forsteriana)": { wateringDays: 10, mistingDays: 7, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Maranta (Prayer Plant)": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-75°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Monstera Deliciosa": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Well-draining peat-based mix", toxicity: "Toxic" },
"Parlor Palm (Chamaedorea elegans)": { wateringDays: 7, mistingDays: 14, repotMonths: 24, temperature: "65-80°F", soilType: "Well-draining potting mix", toxicity: "Non-toxic" },
"Peace Lily (Spathiphyllum)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Rich, well-draining soil", toxicity: "Toxic" },
"Philodendron (Philodendron spp.)": { wateringDays: 10, mistingDays: 14, repotMonths: 18, temperature: "65-80°F", soilType: "Peat-based soil mix", toxicity: "Toxic" },
"Pothos (Epipremnum aureum)": { wateringDays: 10, mistingDays: 30, repotMonths: 18, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"ZZ Plant (Zamioculcas zamiifolia)": { wateringDays: 21, mistingDays: null, repotMonths: 24, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Anthurium": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining peat-based mix", toxicity: "Toxic" },
"Arrowhead Vine (Syngonium podophyllum)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Baby Rubber Plant (Peperomia obtusifolia)": { wateringDays: 10, mistingDays: 14, repotMonths: 18, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Bird's Nest Fern (Asplenium nidus)": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "60-80°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Blue Myrtle Cactus (Myrtillocactus geometrizans)": { wateringDays: 21, mistingDays: null, repotMonths: 24, temperature: "70-90°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"Burro's Tail (Sedum morganianum)": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-75°F", soilType: "Well-draining cactus mix", toxicity: "Non-toxic" },
"Caladium": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Rich, well-draining soil", toxicity: "Toxic" },
"Chinese Evergreen (Aglaonema)": { wateringDays: 10, mistingDays: 7, repotMonths: 18, temperature: "65-80°F", soilType: "Well-draining potting mix", toxicity: "Toxic" },
"Christmas Cactus (Schlumbergera bridgesii)": { wateringDays: 10, mistingDays: null, repotMonths: 24, temperature: "60-70°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Croton (Codiaeum variegatum)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Desert Rose (Adenium obesum)": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-90°F", soilType: "Sandy, well-draining soil", toxicity: "Toxic" },
"English Ivy (Hedera helix)": { wateringDays: 7, mistingDays: 5, repotMonths: 12, temperature: "50-70°F", soilType: "Rich, well-draining soil", toxicity: "Toxic" },
"Ficus Audrey (Ficus benghalensis)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Flaming Katy (Kalanchoe blossfeldiana)": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Golden Barrel Cactus (Echinocactus grusonii)": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "50-85°F", soilType: "Sandy cactus mix", toxicity: "Non-toxic" },
"Heartleaf Philodendron (Philodendron hederaceum)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Jade Plant (Crassula ovata)": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "60-75°F", soilType: "Cactus/succulent soil", toxicity: "Toxic" },
"Lady Palm (Rhapis excelsa)": { wateringDays: 7, mistingDays: 7, repotMonths: 24, temperature: "60-80°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Oxalis (Oxalis triangularis)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Peperomia Watermelon (Peperomia argyreia)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Moon Cactus": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"Prickly Pear Cactus": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "65-85°F", soilType: "Sandy cactus mix", toxicity: "Non-toxic" },
"Silver Velvet Alocasia": { wateringDays: 7, mistingDays: 3, repotMonths: 12, temperature: "65-80°F", soilType: "Moist, well-draining soil", toxicity: "Toxic" },
"Pink Polka Dot Plant": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-75°F", soilType: "Rich, well-draining soil", toxicity: "Non-toxic" },
"Calathea White Fusion": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-80°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Mermaid Tail Cactus": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "70-90°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"Spiral Cactus": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "70-90°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"Boobie Cactus": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "70-90°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"Cuddly Cactus": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "70-90°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"Trailing Hoya Heart": { wateringDays: 10, mistingDays: 7, repotMonths: 18, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Monstera Thai Constellation": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Well-draining peat-based mix", toxicity: "Toxic" },
"Snake Plant Black Gold": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Snake Plant Moonshine": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Snake Plant Silver Flame": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Black ZZ Plant": { wateringDays: 21, mistingDays: null, repotMonths: 24, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Dieffenbachia Sublime": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-75°F", soilType: "Rich, well-draining soil", toxicity: "Toxic" },
"Maranta Red": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-75°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Large Peruvian Apple Cactus": { wateringDays: 21, mistingDays: null, repotMonths: 36, temperature: "70-90°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"Olive Tree": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-85°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Philodendron Xanadu": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Cast Iron Plant": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-75°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Maidenhair Fern": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "60-70°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Calathea Medallion": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-80°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Lightning Jewel Orchid": { wateringDays: 7, mistingDays: 3, repotMonths: 12, temperature: "65-75°F", soilType: "Well-draining orchid mix", toxicity: "Non-toxic" },
"Phalaenopsis Orchid": { wateringDays: 7, mistingDays: 3, repotMonths: 12, temperature: "65-75°F", soilType: "Well-draining orchid mix", toxicity: "Non-toxic" },
"Bird of Paradise": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Rich, well-draining soil", toxicity: "Toxic" },
"Fiddle Leaf Fig": { wateringDays: 7, mistingDays: null, repotMonths: 12, temperature: "65-75°F", soilType: "Loamy, well-draining soil", toxicity: "Toxic" },
"Philodendron Silver": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Petite Snake Plant": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Monstera Deliciosa": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Well-draining peat-based mix", toxicity: "Toxic" },
"ZZ Plant": { wateringDays: 21, mistingDays: null, repotMonths: 24, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Rubber Tree": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Peace Lily": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Rich, well-draining soil", toxicity: "Toxic" },
"Golden Pothos": { wateringDays: 10, mistingDays: 30, repotMonths: 18, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Calathea Musaica": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-80°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Prayer Plant": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-75°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Snake Plant Laurentii": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "60-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Philodendron Brasil": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Anthurium": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining peat-based mix", toxicity: "Toxic" },
"Spider Plant": { wateringDays: 7, mistingDays: 14, repotMonths: 18, temperature: "65-75°F", soilType: "Well-draining potting mix", toxicity: "Non-toxic" },
"Polka Dot Begonia": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Silver Leaf Philodendron": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Black Velvet Alocasia": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Bird's Nest Anthurium": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"String of Pearls": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "70-85°F", soilType: "Cactus mix", toxicity: "Toxic" },
"String of Hearts": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Toxic" },
"String of Bananas": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Toxic" },
"String of Dolphins": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Toxic" },
"String of Turtles": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Nickels": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Rubies": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Beads": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Watermelons": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Needles": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Buttons": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Coins": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Stars": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Non-toxic" },
"String of Hearts Variegated": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Toxic" },
"String of Pearls Variegated": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "70-85°F", soilType: "Cactus mix", toxicity: "Toxic" },
"String of Dolphins Variegated": { wateringDays: 14, mistingDays: null, repotMonths: 24, temperature: "65-80°F", soilType: "Cactus mix", toxicity: "Toxic" },
"Chinese Money Plant (Pilea peperomioides)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "60-75°F", soilType: "Well-draining potting mix", toxicity: "Non-toxic" },
"China Doll Plant (Radermachera sinica)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Air Plant (Tillandsia)": { wateringDays: 7, mistingDays: 2, repotMonths: null, temperature: "60-80°F", soilType: "No soil needed", toxicity: "Non-toxic" },
"Heartleaf Philodendron": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Prayer Plant (Maranta leuconeura)": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-75°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Calathea Orbifolia": { wateringDays: 5, mistingDays: 3, repotMonths: 12, temperature: "65-80°F", soilType: "Moist, well-draining soil", toxicity: "Non-toxic" },
"Alocasia Polly": { wateringDays: 7, mistingDays: 3, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Peperomia Rosso": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Non-toxic" },
"Ficus Benjamina (Weeping Fig)": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-75°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Ficus Audrey": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Monstera Adansonii": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Monstera Peru": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Monstera Siltepecana": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-85°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Philodendron Micans": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Philodendron Birkin": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Philodendron Pink Princess": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Philodendron White Knight": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Philodendron White Wizard": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Philodendron White Princess": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" },
"Philodendron Florida Ghost": { wateringDays: 7, mistingDays: 7, repotMonths: 12, temperature: "65-80°F", soilType: "Well-draining soil", toxicity: "Toxic" }
};

export default plantData;